title: Jini Kim
author:
  name: Jini Kim
  email: jinik@andrew.cmu.edu
description: > # this means to ignore newlines until "show_excerpts:"

show_excerpts: false # set to true to show excerpts on the homepage

permalink: /:title

google_analytics: G-D98LL0KWLR

url: "https://jinikimcmu.github.io/" # the base hostname & protocol for your site
  
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

collections:
  publication:
    output: true

theme: minima